version : '1'
services :
  nginx :
    container_name : nginx
    build :
      context : .
      dockerfile : nginx.dockerfile
    links :
      - node1 : node1
      - node2 : node2
    ports :
      - "80:80"
    env_file :
      - ./config/app.${APP_ENV}.env
    networks :
      - acelabs-network

  node1 :
    container_name : node-ace-1
    build :
      context : .
      dockerfile : node.dockerfile
    ports :
      - "8080"
    env_file :
      - ./config/app.${APP_ENV}.env
    networks :
      - acelabs-network

  node2 :
    container_name : node-ace-2
    build :
      context : .
      dockerfile : node.dockerfile
    ports :
      - "8080"
    env_file :
      - ./config/app.${APP_ENV}.env
    networks :
      - acelabs-network

  main-hub :
    image : selenium/hub
    ports :
      - 4444:4444

  firefox-debug :
    image : selenium/node-firefox-debug
    ports :
      - 4566
    depends_on :
      - main-hub
    environment :
      HUB_HOST : main-hub

  chrome-debug :
    image : selenium/node-chrome-debug
    ports :
      - 4577
    depends_on :
      - main-hub
    environment :
      HUB_HOST : main-hub

  networks : 
    acelabs-network :
      driver : bridge


