# version : '3.3'

# services :
  # nginx :
  #   image : nginx
  #   build :
  #     context : ./web-fe
  #     dockerfile : nginx.dockerfile
  #   links :
  #     - node1:node1
  #     # - node2 : node2
  #   ports :
  #     - "80:80"
  #   # env_file :
  #   #   - ./config/app.${APP_ENV}.env
  #   # networks :
  #   #   - acelabs-network

  # node1 :
  #   image : node-ace-1
  #   build :
  #     context : ../node-api
  #     dockerfile : node.dockerfile
  #   ports :
  #     - "8080:9000"
    # env_file :
    #   - ./config/app.${APP_ENV}.env
    # networks :
    #   - acelabs-network

  # node2 :
  #   container_name : node-ace-2
  #   build :
  #     context : .
  #     dockerfile : node.dockerfile
  #   ports :
  #     - "8080"
  #   env_file :
  #     - ./config/app.${APP_ENV}.env
  #   networks :
  #     - acelabs-network

  # networks : 
  #   acelabs-network :
  #     driver : bridge

  # https://github.com/mikesir87/docker-selenium-grid-demo

  # run - docker-compose up --force-recreate --abort-on-container-exit

  # hub:
  #   container_name: thehub
  #   image: selenium/hub

  # firefox:
  #   image: selenium/node-firefox
  #   links:
  #     - hub

  # chrome:
  #   image: selenium/node-chrome
  #   links:
  #     - hub

  # mvn:
  #   image: maven:3.3.9-jdk-8
  #   volumes:
  #     - ./selenium-cucumber:/usr/src/mvn-src
  #   working_dir: /usr/src/mvn-src
  #   command: mvn clean test -Dselenium-hub.host=hub
  #   links:
  #     - hub
  #     - firefox
  #     - chrome

version : '3.3'

services :
  nginx :
    container_name: theweb
    image : nginx
    build :
      context : ./web-fe
      dockerfile : nginx.dockerfile
    links :
      - node1:node1
      # - node2 : node2
    ports :
      - "80:80"
    # env_file :
    #   - ./config/app.${APP_ENV}.env
    # networks :
    #   - acelabs-network

  node1 :
    image : node-ace-1
    build :
      context : ./node-api
      dockerfile : node.dockerfile
    ports :
      - "8080:9000"
    # env_file :
    #   - ./config/app.${APP_ENV}.env
    # networks :
    #   - acelabs-network

  hub:
    container_name: thehub
    image: selenium/hub
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  mvn:
      image: maven:3.3.9-jdk-8
      volumes:
        - ./selenium-cucumber:/usr/src/mvn-src
      working_dir: /usr/src/mvn-src
      command: mvn clean test -Dselenium-hub.host=hub
      links:
        - hub
        - firefox
        - nginx
        # - chrome