# version : '3.3'

# services :
  # nginx :
  #   image : nginx
  #   build :
  #     context : ../web-fe
  #     dockerfile : nginx.dockerfile
  #   links :
  #     - node1:node1
  #     # - node2 : node2
  #   ports :
  #     - "80:80"
  #   # env_file :
  #   #   - ./config/app.${APP_ENV}.env
  #   # networks :
  #   #   - acelabs-network

  # node1 :
  #   image : node-ace-1
  #   build :
  #     context : ../node-api
  #     dockerfile : node.dockerfile
  #   ports :
  #     - "8080:9000"
    # env_file :
    #   - ./config/app.${APP_ENV}.env
    # networks :
    #   - acelabs-network

  # node2 :
  #   container_name : node-ace-2
  #   build :
  #     context : .
  #     dockerfile : node.dockerfile
  #   ports :
  #     - "8080"
  #   env_file :
  #     - ./config/app.${APP_ENV}.env
  #   networks :
  #     - acelabs-network

  # firefox :
  #   image : selenium/node-firefox-debug
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   # ports :
  #   #   - 4566
  #   depends_on :
  #     - hub
  #   environment :
  #     HUB_HOST : hub

  # chrome :
  #   image : selenium/node-chrome-debug
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   ports :
  #     - 4577
  #   depends_on :
  #     - hub
  #   environment :
  #     HUB_HOST : hub

  # hub :
  #   image : selenium/hub
  #   ports :
  #     - "4444:4444"

  # networks : 
  #   acelabs-network :
  #     driver : bridge

  # https://github.com/mikesir87/docker-selenium-grid-demo

  # run - docker-compose up --force-recreate --abort-on-container-exit
  
  hub:
    image: selenium/hub

  firefox:
    image: selenium/node-firefox
    links:
      - hub

  chrome:
    image: selenium/node-chrome
    links:
      - hub

  mvn:
    image: maven:3.3.9-jdk-8
    volumes:
      - ./selenium-cucumber:/usr/src/mvn-src
    working_dir: /usr/src/mvn-src
    command: mvn clean test -Dselenium-hub.host=hub
    links:
      - hub
      - firefox
      - chrome
